services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: prj_ed11_postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rotas_aereas_bfs

    ports:
      - "5433:5432"

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: